name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4]

    name: PHP ${{ matrix.php }}

    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
    - name: Run composer
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader
    - name: Run phpunit
      run: vendor/bin/phpunit --coverage-text
    - name: Run phpcs
      run: vendor/bin/phpcs --standard=PSR12 --colors -n src tests

